### ISSUE TITLE
The point of base64

### ISSUE THREAD

**Issue by Krzysiu** [SticklyMan/egginc-epic-research-calc#5]
Is there any point of base64 encode/decode? It doesn't hurt, but it's additional code, which is unnecessary and every unneeded code is a potential source of bugs/one more thing to analyze etc. - there's no non-ASCII chars in resulting JSON, so there's no compatibility issues. Sometimes it could serve as very basic protection against manipulating results by newbies, but here everything's editable. It just adds the standard base64 33% overhead.

PS: That's very minor issue - I love your webapp - minimalistic, simple, nice, does exactly what's supposed to do.

**Comment by SticklyMan** [comment]
No idea! Less likely to freak out because of newlines? lol. I'm open to alternatives (or even replacing it with straight up JSON). I would want to maintain backwards compatibility with base64 regardless.

Glad you enjoy it! The style could use some work (responsiveness on mobile), but otherwise it was just a quick and dirty thing I threw together. :)

**Comment by Krzysiu** [comment]
Well, after a bit of thinking I think it's better to keep it that way... In the bandwidth/disk space aspect it's not a problem and while it could be done differently, two possible formats would just complicate code. JSON could be used without newlines, i.e. minimized one, but well...

If you are perfectionist and that overhead is stain on purity ;) I can provide some alternatives, but if you are ok with it, I'm ok as well :) Thanks again and sorry for late reply!

For now I'm taking the liberty of closing this issue with a **reason: purism and microoptimizaton**.
